### PR TITLE
fix - removed ignore prefixs in tests

### PR DESCRIPTION
**Pull request by ThiagoRouge**

### CODE REVIEW

**Review by baur-krykpayev — COMMENTED** [review]
what about the other test file?

**Comment by ThiagoRouge** [comment]
there are no other tests with the ignore prefix

**Comment by baur-krykpayev** [comment]
> there are no other tests with the ignore prefix

yes, in this file.

But, please, re-read my previous comment

**Comment by baur-krykpayev** [comment]
please update the PR by deleting the IGNORE from other files

**Pull request closed without merging**
